### ISSUE TITLE
Add "recipients"-field from JWE-spec, to support multiple recipients encryption?

### ISSUE THREAD

**Issue by Arxcis** [decentralized-identity/didcomm-rs#6]
Since a didcomm-message "to"-attribute supports an array of did's, one would naturally want `didcomm-rs` to support the encryption of a message sent to multiple "recipients" according to the `jwe`-spec:

- https://tools.ietf.org/html/rfc7516#section-7.2.1
>   **recipients**
        The "recipients" member value MUST be an array of JSON objects.
        Each object contains information specific to a single recipient.
      This member MUST be present with exactly one array element per recipient, even if some or all the array element values are the empty JSON object "{}" (which can happen when all Header Parameter
      values are shared between all recipients and when no encrypted key
      is used, such as when doing Direct Encryption).

**Example with multiple "to"-dids, but only one shared-secret**
In the `README.md` example only a single pair-wise shared secret is used, even with multiple "to"-dids: https://github.com/decentralized-identity/didcomm-rs/blob/main/tests/send_receive.rs#L45-L60

**Example of JWE produced by `didcomm-rs` today, without "recipients":**
```json
{
  "typ":"JWM",
  "enc":"XC20P",
  "alg":"ECDH-ES+A256KW",
  "iv":[142,224,127,99,142,169,216,98,250,212,27,107,120,74,151,4,233,68,107,75,77,138,121,147],
  "id":10584863993335768629,
  "type":"didcomm/unknown",
  "to":["did:key:z6MkpKtD5e2G7R4S2UYkb8BxcaFZaeCSPAHZuAG3wQ1RigkH"],
  "from":"did:key:z6MkpKtD5e2G7R4S2UYkb8BxcaFZaeCSPAHZuAG3wQ1RigkH",
  "created_time":1616404868,
  "expires_time":3600,
  "ciphertext":[54,146,10,203,59,122,180,181,115,238,184,104,130,148,36,146,75,181,66,49,101,138,31,61,5,118,130,106,182,16,241,174,186,40,99,201,28,179,218,238,2,128,92,177,48,166,34,169,249,186,215,213,166,21,218,224,1,135,54,44,204,103,129,75,145,4,155,134,86,246,216,173,243,112,250,42,40,22,221,39,243,189,57,156,233,243,205,103,14,175,199,174,156,244,225,147,66,190,189,205,156,146,170,198,129,98,16,249,247,128,118,191,187,16,204,128,68,126,192,72,152,243,255,238,24,63,238,171,183,224,126,225,233,26,158,168,208,251,191,233,140,237,243,122,33,0,235,136,35,59,131,146,180,240,34,96,85,89,217,74,121,96,136,166,171,47,10,215,62,68,181,144,139,185,94,103,60,52,79,188,38,90,162,86,121,210,26,82,227,11,104,102,98,49,169,234,50,140,196,209,18,73,114,181,183,51,37,37,49,89,218,126,120,152,119,133,24,29,36,95,57,166,206,153,61,232,185,181,188,193,144,92,100,196,196,157,120,206,113,29,77,97,66,18,84,244,211,94,223,35,201,94,140,117,218,182,174,184,153,243,41,126,235,62,86,36,194,252,39,139,202,209,233,46,91,14,135,140,127,14,85,202,25,140,3,10,64,241,8,227,136,105,33,150,131,241,243,143,216,192,164,136,223,152,150,64,61,161,181,89,29,229,109,79,150,43,102,178,119,169,82,152,16,25,137,85,9,33,115,143,47,4,240,66,193,99,6,53,122,4,159,11,219,169,104,217,171,254,118,147,106,186,208,111,117,225,173,249,244,183,46,236,248,175,196,151,194,42,80,13,39,154,42,115,16,53,119,121,143,24,88,231,215,228,68,119,16,82,137,232,36,9,47,173,28,79,146,248,147,215,233,223,18,86,247,130,178,225,154,214]
}
```

Any thoughts?

**Comment by 35359595** [comment]
hi @Arxcis, work on this is already in progress, but there are still some questions on the spec definition regarding the place of this property within a message in mediated message: [details](https://github.com/decentralized-identity/didcomm-messaging/pull/172)

This matter should be clarified within next couple weeks and implementation will be released.

**Comment by Arxcis** [comment]
Thank you @35359595 :+1: Do you think this issue also is related to https://github.com/decentralized-identity/didcomm-messaging/issues/18, or is that a separate topic?

**Comment by 35359595** [comment]
Not sure TBH. DIDComm v2 spec says nothing specific ATM on this matter except the JWE/JWM relation, which gives the way of implementing multi-receiver JWEs. This might be a way of (partially?) solving it?

> Thank you @35359595 👍 Do you think this issue also is related to [decentralized-identity/didcomm-messaging#18](https://github.com/decentralized-identity/didcomm-messaging/issues/18), or is that a separate topic?

**Comment by 35359595** [comment]
Version 0.4.0 released with support of static secret wrapping per recipient.
Note that API has not changed but works only with `resolve` feature enabled and included resolver atm only did:key (other to follow).
```json
"{"typ":"JWM",
"enc":"XC20P",
"alg":"ECDH-ES+A256KW",
"iv":[35,204,85,47,11,183,42,68,14,214,65,114,138,111,116,60,249,131,45,193,137,227,241,181],"id":10450823329695522987,"type":"application/didcomm-plain+json",
"to":["did:key:z6MkjchhfUsD6mmvni8mCdXHw216Xrm9bQe2mBH1P5RDjVJG","did:key:z6MknGc3ocHs3zdPiJbnaaqDi58NGb4pk1Sp9WxWufuXSdxf"],
"from":"did:key:z6MkiTBz1ymuepAQ4HEHYSF1H8quG5GLVVQR3djdX3mDooWp",
"recepients":[
{"header":{"kty":"oct","use":"enc","key_ops":[],"alg":"ECDH-ES+A256KW","kid":"#z6MkjchhfUsD6mmvni8mCdXHw216Xrm9bQe2mBH1P5RDjVJG"},"encrypted_key":"8iz6jp4IMR5NM-0AouOvGtAanBI7rr1cfi3N9siAHjGiD2jwIu9T7qOrQ5KeVQxX"},
{"header":{"kty":"oct","use":"enc","key_ops":[],"alg":"ECDH-ES+A256KW","kid":"#z6MknGc3ocHs3zdPiJbnaaqDi58NGb4pk1Sp9WxWufuXSdxf"},"encrypted_key":"yFFMxdWjsJRGkk3Z9WwGrmFvoAazl2lorYcB9znP7-FQgmN1z-9ep6x5ecWO-iPs"}],
"ciphertext":[168,112,13,51,8,250,235,155,255,135,88,179,19,119,105,83,5,207,163,124,213,125,222,141,237,186,176,140,62,213,68,225,141,77,244,229,55,200,2,59..."
```

**Comment by Baha-sk** [comment]
Please review Aries [RFC-334](https://github.com/hyperledger/aries-rfcs/tree/master/features/0334-jwe-envelope) specifically about JWE envelopes.

Multi recipients are supported by the JWE spec as well, the above RFC shows examples of multi recipients JWEs, flattened JSON JWEs (single recipient) and compact form JWEs (also single recipient)

**Comment by 35359595** [comment]
> Please review Aries [RFC-334](https://github.com/hyperledger/aries-rfcs/tree/master/features/0334-jwe-envelope) specifically about JWE envelopes.
> 
> Multi recipients are supported by the JWE spec as well, the above RFC shows examples of multi recipients JWEs, flattened JSON JWEs (single recipient) and compact form JWEs (also single recipient)

AFAIK compact serialization was dropped by DIDComm v2 spec...

**Comment by Baha-sk** [comment]
> AFAIK compact serialization was dropped by DIDComm v2 spec...

RFC 334 only shows compact serializations as general JWE examples, it doesn't dictate V2 spec. [RFC 587](https://github.com/hyperledger/aries-rfcs/tree/master/features/0587-encryption-envelope-v2) was created specifically for DIDComm V2 envelope.
